name = "ahmed-portfolio"
main = "src/index.js"
compatibility_date = "2026-09-06"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "ahmed-portfolio-db"
database_id = "ec6c9bd0-dd8f-4823-9d34-384de940bb04"
