name = "ahmed-portfolio"
compatibility_date = "2026-09-06"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "ahmed-portfolio-db"
database_id = "ec6c9bd0-dd8f-4823-9d34-384de940bb04"
